fedrec/communications/worker_manager.py, fedrec/federated_worker.py, fedrec/trainers/base_trainer.py, fedrec/utilities/serialization.py
=> Initial commit for job submission

fedrec/communications/abstract_comm_manager.py, fedrec/communications/comm_manager.py, fedrec/communications/communication_interfaces.py, fedrec/communications/global_comm_stream.py, fedrec/federated_worker.py
This pull request is related to #8.
=> [WIP] Add Asynchronous messaging queue for send and receive functions 

fedrec/communications/comm_manager.py, fedrec/communications/global_comm_stream.py, fedrec/communications/messages.py, fedrec/communications/process_com_manager.py, fedrec/communications/worker_manager.py, fedrec/federated_worker.py
=> Message Token Class 

fedrec/communications/comm_manager.py, fedrec/multiprocessing/process_manager.py
=> Message Future Dict

executor.py, fedrec/communications/kafka_interfaces.py, fedrec/communications/messages.py, fedrec/multiprocessing/jobber.py, fedrec/multiprocessing/mpi_process.py
implements task 3 of #38 and #39
=> support aggregator and trainer in jobber

fedrec/multiprocessing/mpi_process.py
#27 
Added Documentation to MPIProcess Class
=> Added Documentation for MPI Process Class

experiments/dlrm/dlrm_trainer.py, fedrec/multiprocessing/jobber.py, fedrec/python_executors/trainer.py
Adding run and output methods and making dlrm trainer compatible
=> Adding run and output methods and making dlrm trainer compatible

scala_core/src/main/scala/org/nimbleedge/recoedge/Aggregator.scala, scala_core/src/main/scala/org/nimbleedge/recoedge/Main.scala, scala_core/src/main/scala/org/nimbleedge/recoedge/Orchestrator.scala, scala_core/src/main/scala/org/nimbleedge/recoedge/Supervisor.scala, scala_core/src/main/scala/org/nimbleedge/recoedge/models/Identifier.scala
Addition of all the basic messages and complete Identifier class
=> Addition of All Basic Messages and Complete Identifier Class

docs/Tutorial-Part-1-introduction_to_fl.md, docs/Tutorial-Part-2-starting_with_nimbleedge.md
updated missing links from documentation
=> Doc update: missing links

environment.yml, fedrec/communications/messages.py, test/dummy_exec.py, test/test_config.yml, test/test_serializer.py
=> Add unit test for serialiser

train.py
A possible fix for the issue "Documentation: Write Inline Documentation for train.py #93."
=> Added Inline Documentation

tests/test_configs/test_config.yml, tests/unit_tests/test_message.py
added testing for message.py
#104 
None
=> added testing for message.py

fedrec/communications/messages.py
Added inline documentation for communications/message.py
#137
=> add inline documentation for communications/message.py

README.md, datasets/femnist/femnist_processor.py
Made changes to all the errors and modifications mentioned in the issue
Issue #Tag the issue here
=> Updated readme file

docs/source/tutorials/Tutorial-Part-7-local_training_ios.rst
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
Issue #Tag the issue here
=> Updated local_training_ios

docs/source/tutorials/Tutorial-Part-5-data_loading_and_processing.rst
Updates docs by updating the data_loading_and_processing tutorial section
=> Updated dataloaders in data_loading_and_processing

docs/source/tutorials/Tutorial-Part-5-data_loading_and_processing.rst
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
Issue #Tag the issue here
=> Added example for Data Loaders and Preprocessing

docs/source/tutorials/Tutorial-Part-5-data_loading_and_processing.rst
Updates the tutorial for Data Processors and Data Loaders
Issue #237
=> Updates the tutorial for Data Processors and Data Loaders

docs/source/tutorials/Tutorial-Part-4-deployment.rst, fedrec/multiprocessing/jobber.py
After going through the tutorial 4 documentation I spotted a little typographical error that I corrected. In some cases the sentences where incomplete.
Issue #250
=> Docmentation: Fixed a typographical error found in Tutorial-Part-4-deployment.rst document

docs/source/tutorials/Tutorial-Part-1-introduction_to_fl.rst, docs/source/tutorials/Tutorial-Part-2-starting_with_nimbleedge.rst, docs/source/tutorials/Tutorial-Part-3-simulating_fl_cycle.rst, docs/source/tutorials/Tutorial-Part-6-local_training_android.rst, docs/source/tutorials/Tutorial-Part-7-local_training_ios.rst, docs/source/tutorials/Tutorial-Part-8-customization.rst
corrected grammatical mistakes
Issue #265 
=> Grammer correction 

docs/source/getting_started.rst
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
Issue #270 
=> fixed link

docs/source/getting_started.rst
This PR fixes issue #274 
Issue #274 the issue here
=> Updated the Getting Started docs

CONTRIBUTING.md, README.md
=> updated readme and contributing.md file

fedrec/communication_interfaces/abstract_comm_manager.py, fedrec/communication_interfaces/kafka_interface.py, fedrec/communication_interfaces/zeroMQ_interface.py
added inline docs for methods and class along with examples
Issue #269  the issue here
None
=> updated communication_interfaces folder

fedrec/utilities/logger.py
added inline docs for methods and class
Issue #269  the issue here
none
=> updated logger.py file

.github/labeler.yml, .github/workflows/labeler.yml
This PR will enable automatic labeling of PR. Which will help make it easy for reviewers/maintainers to review the PR.
=> Adds labeler action for pull requests

fedrec/modules/embeddings.py
added inline docs for methods and class
Issue #269  the issue here
None
=> updated embeddings.py

fedrec/utilities/registry.py
This PR adds inline documentation to the registry.py file.
Issue #269
=> added docs for registry

fedrec/multiprocessing/jobber.py
This PR adds inline documentation to the jobber.py file.
Issue #269
=> added docs for jobber.py

fedrec/user_modules/envis_trainer.py
This PR adds inline documentation to the envis_trainer.py file.
Issue #269
=> added doc to envis_trainer.py

fedrec/user_modules/envis_aggregator.py
This PR adds inline documentation to the envis_aggregator.py file.
Issue #269
=> added docs for envis_aggregator.py

fedrec/user_modules/envis_preprocessor.py
This PR adds inline documentation to the envis_preprocessor.py file.
Issue #269
=> added doc for envis_preprocessor.py

fedrec/python_executors/base_actor.py
This PR adds inline documentation to the base_actor.py file.
Issue #269
=> added doc for base_actor.py

fedrec/utilities/cuda_utils.py, fedrec/utilities/io_utils.py
adding inline documentation to the files in utilities folder
Issue #269  the issue here
=> updated io_utils.py
